name: Publish Packages

on:
  push:
    branches: [ prerelease ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.403
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Unit Test
      run: dotnet test
    - name: Publish Graffle.FlowSdk
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: Graffle.FlowSdk/Graffle.FlowSdk.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: 0.1.0-prerelease